### ISSUE TITLE
Include GNU parallel in the singularity image?

### ISSUE THREAD

**Issue by akiledal** [nick-youngblut/traitar3#2]
The singularity image currently doesn't support parallel execution.

**Comment by nick-youngblut** [comment]
I didn't modify the singularity image; that image is from the initial fork. PRs are always welcome

**Comment by Agihawi** [comment]
Hi,

I have added parallel to the singularity image file. Haven't tested it out in the context of the software, but it should be fine now.

This does include an additional line in the singularity definition file. I can share if you need.

Abe

**Comment by nick-youngblut** [comment]
>This does include an additional line in the singularity definition file. I can share if you need.

Great! Just send a PR, and I'll accept

**Comment by Agihawi** [comment]
#3 Pull request should have gone through.

Let me know if all is ok @akiledal
