### ISSUE TITLE
Can we make it bioconda installable

### ISSUE THREAD

**Issue by SilasK** [nick-youngblut/traitar3#4]
I suggest creating a release 3.0.1 what do you think?

**Comment by nick-youngblut** [comment]
Sure. I didn't want to step on the toes of the original developer and make it seem like I'm taking credit for creating a new version of traitar, but it seems that the original developer is not going to update traitar and there still is interest for using traitar, so I'm onboard with creating a bioconda recipe. I'll hopefully have some time later today to work on this.

**Comment by nick-youngblut** [comment]
I've created the new release: https://github.com/nick-youngblut/traitar3/releases/tag/3.0.1, but I probably won't have time in the near future to create a bioconda recipe. Please go ahead and create one if you'd like traitar3 available on bioconda in the very near future.
